### ISSUE TITLE
How to run this thing?

### ISSUE THREAD

**Issue by dirtbag** [ercpe/amavisvt#9]
The installation instructions are very much lacking for us non-gentoo users.. 
So I managed to run 
python setup.py install    and that seemed to install it..
but now what? I cant find a binary/daemon to run. 
Please hit me with a clue-stick.

regards,
db

**Comment by rbicelli** [comment]
First, copy the sample configuration file in /etc/amavisvtd.cfg and change settings, expecially database path and socket path to something writable.
Then cd into amavisvt dir and launch it with `python amavisvtd.py`.

**Comment by maxxer** [comment]
Setup on Ubuntu16
```
apt install python3-pip
pip3 install -r requirements.txt
python3 setup.py install
```
this will install in `/usr/local/lib/python3.5/dist-packages/amavisvt-0.5.3-py3.5.egg/amavisvt`

Copy and edit config file to suit your needs, expecially to add your VT API key
```
cp amavisvt_example.cfg /etc/amavisvt.cfg
```

Now run  (change the first if you used a different path in config)
```
mkdir /var/lib/amavisvt/ 
python3 /usr/local/lib/python3.5/dist-packages/amavisvt-0.5.3-py3.5.egg/amavisvt/amavisvtd.py
```

Now adjust your amavisd config as per readme
